language: c

os:
  - linux

install:
  - wget --quiet https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.tar.gz
  - tar xzvf hugo_0.58.3_Linux-64bit.tar.gz
  - export PATH=$PATH:$PWD


before_script:
  - git clone https://github.com/SZLforGithub/louis-hugo.git
script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
  local-dir: public
  repo: SZLforGithub/SZLforGithub.github.io
  target-branch: master
  